import { Book, User } from '@/types';

export const allBooks: Book[] = [
    {
        id: 1,
        title: "미드나잇 라이브러리",
        author: "매트 헤이그",
        coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80",
        publisher: "인플루엔셜",
        publicationDate: "2021-04-28",
        pages: 400,
        description: "죽음의 문턱에서 만난 한밤의 도서관, 그곳에서 인생의 두 번째 기회를 얻다.",
        genre: "소설",
        rating: 4.5,
        tags: ["판타지", "힐링"],
        stock: 10,
    },
    {
        id: 2,
        title: "달러구트 꿈 백화점",
        author: "이미예",
        coverImage: "https://images.unsplash.com/photo-1593349349909-478631b2d39d?w=800&q=80",
        publisher: "팩토리나인",
        publicationDate: "2020-07-08",
        pages: 304,
        description: "잠들어야만 입장할 수 있는 비밀 상점, 그곳에서 가장 인기 있는 꿈을 만나다.",
        genre: "소설",
        rating: 4.7,
        tags: ["판타지", "성장"],
        stock: 15,
    },
    {
        id: 3,
        title: "아몬드",
        author: "손원평",
        coverImage: "https://images.unsplash.com/photo-1589998059171-988d887df646?w=800&q=80",
        publisher: "창비",
        publicationDate: "2017-03-31",
        pages: 264,
        description: "감정을 느끼지 못하는 소년의 특별한 성장 이야기.",
        genre: "소설",
        rating: 4.6,
        tags: ["성장", "드라마"],
        stock: 8,
    },
    {
        id: 4,
        title: "불편한 편의점",
        author: "김호연",
        coverImage: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800&q=80",
        publisher: "나무옆의자",
        publicationDate: "2021-04-20",
        pages: 268,
        description: "서울역의 작은 편의점에서 벌어지는 따뜻하고 유쾌한 이웃들의 이야기.",
        genre: "소설",
        rating: 4.8,
        tags: ["힐링", "일상"],
        stock: 20,
    },
    {
        id: 5,
        title: "팩트풀니스",
        author: "한스 로슬링",
        coverImage: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=800&q=80",
        publisher: "김영사",
        publicationDate: "2019-03-27",
        pages: 460,
        description: "세상을 오해하는 10가지 이유와 세상이 생각보다 괜찮은 이유에 대하여.",
        genre: "교양",
        rating: 4.9,
        tags: ["데이터", "통계", "인사이트"],
        stock: 12,
    },
];

export const featuredBooks: Book[] = allBooks.slice(0, 5);

export const mockUsers: User[] = [
    {
        id: 1,
        username: "독서왕",
        email: "reader@example.com",
        avatar: "https://i.pravatar.cc/150?u=reader",
        isAdmin: false,
    },
    {
        id: 2,
        username: "관리자",
        email: "admin@example.com",
        avatar: "https://i.pravatar.cc/150?u=admin",
        isAdmin: true,
    },
];